<?php

namespace AppBundle\Repository;

/**
 * TodoManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
